### ISSUE TITLE
Add logging tags in each stack file

### ISSUE THREAD

**Issue by abhi4578** [datakaveri/iudx-deployment#639]
Add logging tags to each stack file to get container name and id as labels in logs 
```
 logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
        tag: "{\"name\":\"{{.Name}}\",\"id\":\"{{.ID}}\"}"
```
